#!/bin/sh

if ! uci -q get uhttpd.easyclash >/dev/null; then
	uci add uhttpd easyclash
	uci set uhttpd.easyclash.listen_http='0.0.0.0:8080'
	uci set uhttpd.easyclash.index_page='cgi-bin/luci/admin/services/easyclash/nodes'
	uci set uhttpd.easyclash.home='/www'
	uci set uhttpd.easyclash.cgi_prefix='/cgi-bin'
	uci commit uhttpd
	/etc/init.d/uhttpd restart
fi

exit 0
