#!/bin/sh

if ! uci -q get uhttpd.easyclash >/dev/null 2>&1; then
	uci set uhttpd.easyclash=uhttpd
	uci set uhttpd.easyclash.listen_http='0.0.0.0:8080'
	uci set uhttpd.easyclash.index_page='index.html'
	uci set uhttpd.easyclash.home='/www'
	uci set uhttpd.easyclash.cgi_prefix='/cgi-bin'
	uci commit uhttpd
	/etc/init.d/uhttpd restart
fi

exit 0
